### ISSUE TITLE
Password for MPD

### ISSUE THREAD

**Issue by netmindz** [GioF71/mpd-alsa-docker#284]
I can't see in the docs how you set passwords and their permissions for MPD itself

**Comment by GioF71** [comment]
There is no support for that, but it seems reasonable to add. I thought nobody was interested on these features, I guess I was wrong.

**Comment by GioF71** [comment]
Hello, can you try one of [these images](https://hub.docker.com/r/giof71/mpd-alsa/tags?page=1&name=f284b01)?
For example `giof71/mpd-alsa:feature-f284b01-bullseye-0.23.12`

For reference, have a look at [this branch](https://github.com/GioF71/mpd-alsa-docker/tree/284-password-for-mpd), the changes are in the README.

Specifically, you should be able to set:

DEFAULT_PERMISSIONS
LOCAL_PERMISSION
HOST_PERMISSIONS (and HOST_PERMISSIONS_1, HOST_PERMISSIONS_2, and so on)
PASSWORD (and PASSWORD_1, PASSWORD_2, and so on)

Please let me know if this works for you and/or if something is missing.

**Comment by GioF71** [comment]
This has been released and is available from version 2023-05-20 an on. 
Please reopen if something is wrong and/or missing.
