### ISSUE TITLE
[Feature] Add an environment variable which allows using custom mpd.conf file

### ISSUE THREAD

**Issue by vari** [GioF71/mpd-alsa-docker#356]
It would be great to have an environment variable which can be used to override the generation of the mpd.conf file in the container or specify a path to a custom mpd.conf file to use instead of the default one. This will enable use cases not currently supported by the container and provide a mechansim to provide a custom conf file in case there is a bug with the generated config in the future.

(Separate issue created as per request in #355 )

**Comment by GioF71** [comment]
Hello, I implemented this using the (already existing) volume /user/config
Just place (or anyway mount) a file named `override.mpd.conf` to use that file instead of the generated configuration file.
Hope this will work for you, enjoy!
