### ISSUE TITLE
[Doc] Fix typo for mixer type variable name in shout output doc

### ISSUE THREAD

**Issue by vari** [GioF71/mpd-alsa-docker#362]
The env variables table for the shout plugin in the [doc](https://github.com/GioF71/mpd-alsa-docker/blob/main/doc/shout-additional-outputs.md) incorrectly says that `SHOUT_MIXER_TYPE` sets the mixer type. 

The mixer type is actually set by `SHOUT_OUTPUT_MIXER_TYPE` (as per the [build_additional.sh](https://github.com/GioF71/mpd-alsa-docker/blob/main/app/bin/build-additional.sh#L333) script).

**Comment by GioF71** [comment]
Done, thank you!
